// Sinh tự động bởi scripts/gen_icons_map.mjs — ảnh item (Flow → cắt nền) dùng cho card và ô tay
export const ICONS = {
  'bac-ha': './icons/bac-ha.png',
  'banh-da': './icons/banh-da.png',
  'banh-hoi': './icons/banh-hoi.png',
  'bap-bo': './icons/bap-bo.png',
  'bo-la-lot': './icons/bo-la-lot.png',
  'bo-tai': './icons/bo-tai.png',
  'bo-vien': './icons/bo-vien.png',
  'bun-bo-broth-ready': './icons/bun-bo-broth-ready.png',
  'bun-to': './icons/bun-to.png',
  'bun': './icons/bun.png',
  'ca-chien': './icons/ca-chien.png',
  'ca-chua': './icons/ca-chua.png',
  'can-nuoc': './icons/can-nuoc.png',
  'cha-ca': './icons/cha-ca.png',
  'cha-chien': './icons/cha-chien.png',
  'cha-cua': './icons/cha-cua.png',
  'cha-hap': './icons/cha-hap.png',
  'cha-lua': './icons/cha-lua.png',
  'cha-re': './icons/cha-re.png',
  'chao-ap-ca-ready': './icons/chao-ap-ca-ready.png',
  'chao-ap-ca': './icons/chao-ap-ca.png',
  'chao-long': './icons/chao-long.png',
  'chao-suon': './icons/chao-suon.png',
  'chen-chanh-ready': './icons/chen-chanh-ready.png',
  'chen-dau-phong-ready': './icons/chen-dau-phong-ready.png',
  'chen-mam-tom-ready': './icons/chen-mam-tom-ready.png',
  'chen-ot-ready': './icons/chen-ot-ready.png',
  'chen-rau-ready': './icons/chen-rau-ready.png',
  'cot-cua': './icons/cot-cua.png',
  'crab-broth-ready': './icons/crab-broth-ready.png',
  'dau-hu': './icons/dau-hu.png',
  'dau-phong-rang': './icons/dau-phong-rang.png',
  'dia-lon': './icons/dia-lon.png',
  'dia-thi-la-ready': './icons/dia-thi-la-ready.png',
  'do-chua': './icons/do-chua.png',
  'dry-bowl': './icons/dry-bowl.png',
  'dua-leo': './icons/dua-leo.png',
  'extra-bowl': './icons/extra-bowl.png',
  'fish-broth-ready': './icons/fish-broth-ready.png',
  'goc-hanh-la': './icons/goc-hanh-la.png',
  'gung': './icons/gung.png',
  'hanh-la': './icons/hanh-la.png',
  'hanh-phi': './icons/hanh-phi.png',
  'hanh-tay': './icons/hanh-tay.png',
  'huyet': './icons/huyet.png',
  'kinh-gioi': './icons/kinh-gioi.png',
  'la-sach': './icons/la-sach.png',
  'mam-dan': './icons/mam-dan.png',
  'mam-tom': './icons/mam-tom.png',
  'mieng-nuoc': './icons/mieng-nuoc.png',
  'mo-hanh': './icons/mo-hanh.png',
  'nam': './icons/nam.png',
  'ngo-ri-ngo-gai': './icons/ngo-ri-ngo-gai.png',
  'noodle-basket': './icons/noodle-basket.png',
  'nuoc-bun-bo': './icons/nuoc-bun-bo.png',
  'nuoc-ca': './icons/nuoc-ca.png',
  'nuoc-cot-chanh': './icons/nuoc-cot-chanh.png',
  'nuoc-pho': './icons/nuoc-pho.png',
  'ot-do': './icons/ot-do.png',
  'pho-bowl': './icons/pho-bowl.png',
  'pho-noodle': './icons/pho-noodle.png',
  'porridge-ready': './icons/porridge-ready.png',
  'quay': './icons/quay.png',
  'rau-muong': './icons/rau-muong.png',
  'rau-ram': './icons/rau-ram.png',
  'rau-salad': './icons/rau-salad.png',
  'salad-cut-ready': './icons/salad-cut-ready.png',
  'serving-plate': './icons/serving-plate.png',
  'soup-bowl': './icons/soup-bowl.png',
  'suon-cay': './icons/suon-cay.png',
  'thi-la': './icons/thi-la.png',
  'thit-luoc': './icons/thit-luoc.png',
  'thit-nuong': './icons/thit-nuong.png',
  'tia-to': './icons/tia-to.png',
  'tom': './icons/tom.png',
  'top-mo': './icons/top-mo.png',
  'tray-paper': './icons/tray-paper.png',
  'tray-ready': './icons/tray-ready.png',
  'tray': './icons/tray.png',
  'veg-ready': './icons/veg-ready.png',
  'xa-lach': './icons/xa-lach.png',
  'xoai': './icons/xoai.png',
};
// token đã chế biến dùng ảnh của nguyên liệu gốc (sợi/tô theo loại: 'noodle-drained:bun' → bun, 'bowl-hot:soup-bowl' → soup-bowl)
const BASE = { 'noodle-spoiled': 'pho-noodle', 'bowl-hot': 'pho-bowl', 'bowl-hot:*': 'pho-bowl', 'broth:pour-pho-broth': 'nuoc-pho', 'bo-vien-ready': 'bo-vien', 'tai-dap-ready': 'bo-tai', 'rib-hot': 'suon-cay', 'rib-cut': 'suon-cay', 'rib-ready': 'suon-cay', 'two-bowls-ready': 'extra-bowl', 'cha-ca-ready': 'cha-ca', 'cha-cua-ready': 'cha-cua', 'youtiao-ready': 'quay', 'level1-ready': 'soup-bowl' };
export function iconUrl(tok) {
  if (!tok) return null;
  if (ICONS[tok]) return ICONS[tok];
  if (BASE[tok]) return ICONS[BASE[tok]] || null;
  if (/^(noodle-\w+|bowl-hot):/.test(tok)) return ICONS[tok.split(':')[1]] || ICONS[tok.startsWith('bowl') ? 'pho-bowl' : 'pho-noodle'] || null;
  return null;
}
